name: Save API Result

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    - uses: actions/checkout@v3
    - name: Read .nvmrc
      working-directory: ./typescript/save-api-result
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - run: npm install
      working-directory: ./typescript/save-api-result
    - run: npm run build
      working-directory: ./typescript/save-api-result
    - run: npm run start
      working-directory: ./typescript/save-api-result

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: Automated data pull

        # Optional. Local and remote branch name where commit is going to be pushed
        #  to. Defaults to the current branch.
        #  You might need to set `create_branch: true` if the branch does not exist.
        # branch: data-fetch-${{ steps.date.outputs.date }}

        # Optional. Options used by `git-commit`.
        # See https://git-scm.com/docs/git-commit#_options
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        # file_pattern: data/*.json data/legacy/*.json

        # Optional. Local file path to the repository.
        # Defaults to the root of the repository.
        repository: .

        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
        commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
        commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

        # Optional. Option used by `git-status` to determine if the repository is 
        # dirty. See https://git-scm.com/docs/git-status#_options
        status_options: '--untracked-files=no'

        # Optional. Options used by `git-add`.
        # See https://git-scm.com/docs/git-add#_options
        add_options: '-u'

        # Optional. Options used by `git-push`.
        # See https://git-scm.com/docs/git-push#_options
        push_options: '--force'
        
        # Optional. Disable dirty check and always try to create a commit and push
        skip_dirty_check: true    
        
        # Optional. Skip internal call to `git fetch`
        skip_fetch: true    
        
        # Optional. Skip internal call to `git checkout`
        skip_checkout: true

        # Optional. Prevents the shell from expanding filenames. 
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true

        # Optional. Create given branch name in local and remote repository.
        create_branch: true